### ISSUE TITLE
6.42 release date ?

### ISSUE THREAD

**Issue by davekopecek** [d6lts/drupal#1]
Why was the release date for 6.42 created in 436f4aa rolled back with 3ef9dcf?  This makes it appear that 6.42 was released on 2018-Feb-22, prior to the 3/28 release of the SA-CORE-2018-002 patch.   

[drupal-6.42-release-date.pdf](https://github.com/d6lts/drupal/files/1860595/drupal-6.42-release-date.pdf)

**Comment by dsnopek** [comment]
We always add it and roll it back! That's just how we handle packaging, so that the added information is only on the tag and not the branch. I think the problem you're pointing out is actually in our update status data, though, not the code. I'll look into that and get back to you...

**Comment by dsnopek** [comment]
I've fixed our update status data. Can you try clicking the "Check manually" link on the "Available updates" report and see if that fixes it for you?

**Comment by dsnopek** [comment]
I'm going to close this - feel free to re-open if you're still seeing the problem

**Comment by davekopecek** [comment]
Fixed for me.  Thanks for all your work on d6lts.

[drupal-6.42-release-date-fixed.pdf](https://github.com/d6lts/drupal/files/1861431/drupal-6.42-release-date-fixed.pdf)

**Comment by dsnopek** [comment]
Great! Thanks for reporting and thanks for checking back :-)
