### ISSUE TITLE
Drupal 6 book

### ISSUE THREAD

**Issue by PROMES** [d6lts/drupal#20]
Ik got this message:
Only variables should be passed by reference in /public_html/modules/book/book.module on line 559.

I changed back to the book.module of version 6.44. Two lines where changed into one line, which appears to be not correct.

**Comment by aitala** [comment]
The patch for this issue is https://www.drupal.org/node/1707928

**Comment by dsnopek** [comment]
Committed that patch:

https://github.com/d6lts/drupal/commit/befcc037588dc582f19fb28cc6741a73d59bb2ae
