### ISSUE TITLE
PHP 7.2 compatibility fixes

### ISSUE THREAD

**Issue by Ayesh** [d6lts/drupal#22]
Hi there,
Awesome work on LTS release so far! I'm trying to get an old D6 site to run well on PHP 7.2, and so far, it seems to work. 

PHP 7.2 throws a warning if we try to call `count()` with a parameter that is not an array or implements `\Countable` interface. This raises several warnings in many projects. I will try to send PRs as I work on them. 

Additionally, the function `each()` is deprecated and there are some occasions that this function is used. I will work on PRs for them as well. 

May I suggest that we tag this issue in PHP 7.2 compatibility fixes so they are easy to track?

Thank you.

**Comment by dsnopek** [comment]
Sorry that I missed this! Tagging the issues sounds fine, although we have so few issues and PRs on this GitHub project, it isn't unmanageable without that.
