### ISSUE TITLE
profile.module

### ISSUE THREAD

**Issue by aitala** [d6lts/drupal#25]
Just did the upgrade to 6.46 and am getting the following php error

`Creating default object from empty value in  modules/profile/profile.module on line 493.`

This is occurring on nodes where user profile information is displayed - see https://www.f1m.com/content/kits/brabham-bt48-dutch-gp

The site is still running PHP 5.6.38

Eric

**Comment by Ayesh** [comment]
This is due to PHP 5.4's changes. I remember I came across a bug in taxonomy module as well. 

To fix, replace the following snippet with the one after in `modules/profile/profile.module`.

Replace this:
```
if ($field->value) {
      $variables['profile'][$field->name]->title = check_plain($field->title);
      $variables['profile'][$field->name]->value = $field->value;
      $variables['profile'][$field->name]->type = $field->type;
}
```

with this:
```
if ($field->value) {
      $variables['profile'][$field->name] = $variables['profile'][$field->name] 
        ?  $variables['profile'][$field->name]
        : new stdClass();
      $variables['profile'][$field->name]->title = check_plain($field->title);
      $variables['profile'][$field->name]->value = $field->value;
      $variables['profile'][$field->name]->type = $field->type;
}
```

**Comment by aitala** [comment]
That seems to cover the issue.

**Comment by dsnopek** [comment]
I reproduced this issue and created PR https://github.com/d6lts/drupal/pull/27 to fix this.

It's simpler than the example code given above, because `$variables['profile']` is set to an empty array a couple lines earlier, so there's no way it has an existing value

**Comment by Ayesh** [comment]
Yeah the fix in PR looks cleaner.
