### ISSUE TITLE
MySQL Functions in PHP 7+

### ISSUE THREAD

**Issue by labboy0276** [d6lts/drupal#31]
Hello

I upgraded a site to the latest d6lts version 6.47, when I switch my php version in lando to 7 or 7.1 I get this:

```
Call to undefined function mysql_real_escape_string() 
```

I know all mysql_ functions have been removed in php 7+, so how are you handling this issue on your d6 sites that run php7?

**Comment by Ayesh** [comment]
You can still use mysqli. Drupal 6 has mysqli support.

**Comment by dsnopek** [comment]
You need to make sure your database credentials use 'mysqli://' rather than 'mysql://' and if you're using Drush, you need to update to Drupash 8.1.18.

**Comment by labboy0276** [comment]
Ah that did it, thanks so much!
