### ISSUE TITLE
Illegal string offset 'files' in /modules/upload/upload.module on line 281.

### ISSUE THREAD

**Issue by cjamesrun** [d6lts/drupal#33]
I solved the issue of the attached uploaded files not showing by editing the upload.module: Line 278 - 284
`case 'load':
      $output = '';
      if (variable_get("upload_$node->type", 1) == 1) {
        $output['files'] = upload_load($node);
        return $output;
      }
      break;
`
Changed to 
`case 'load':
      $output = array();
      if (variable_get("upload_$node->type", 1) == 1) {
        $output['files'] = upload_load($node);
        return $output;
      }
      break;
`

**Comment by dsnopek** [comment]
We implemented a different change for this same bug - see https://github.com/d6lts/drupal/blob/6.x/modules/upload/upload.module#L281

I don't recall exactly when we implemented that, but it was a few releases ago, so you should be good with the latest release!
