### ISSUE TITLE
CHANGELOG.txt file not update in release 6.48 and 6.49

### ISSUE THREAD

**Issue by anq4** [d6lts/drupal#34]
Both 6.48 and 6.49 versions have an old CHANGELOG.txt file from version 6.47

**Comment by anq4** [comment]
Also latest 6.50 packet didn't change CHANGELOG.txt

**Comment by dsnopek** [comment]
Sorry, I'm bad about updating the CHANGELOG.txt - will get this fixed soon so that those versions are mentioned at least in the next release (6.51)

**Comment by anq4** [comment]
Thank you very much.
It's a very basic but quick and easy way to check for updates on multiple sites.
