### ISSUE TITLE
substr() in database.inc

### ISSUE THREAD

**Issue by PROMES** [d6lts/drupal#39]
After upgrading to 6.51 I got this warning many many times while running update.php:

warning: substr() expects parameter 1 to be string, array given in /home/photontst/domains/test.photonmagazine.nl/public_html/includes/database.inc on line 358.

my PHP: 7.1.25
my MySQL: 5.6.38

**Comment by drshawnkwang** [comment]
Please see #38. There is also a [Drupal d6lts Issue](https://www.drupal.org/project/d6lts/issues/3052207).

**Comment by dsnopek** [comment]
This should be fixed in #40
