### ISSUE TITLE
Typo in exclude

### ISSUE THREAD

**Issue by jnicola** [d6lts/drupal#48]
https://github.com/d6lts/drupal/blob/c9b85e7b405a592b73335daa266cdcc3015e057e/includes/unicode.inc#L365

Typo. $execlude, needs to be $exclude.

**Comment by dsnopek** [comment]
Thanks! However, that's an old commit. That type-o was fixed in 7aa52e99ed6213e49646409d97f9f8a03ef7fcd0 and I don't think the code with the type-o in it was ever included in a release
