### ISSUE TITLE
Ajax quoting problem with utf8 chars

### ISSUE THREAD

**Issue by neffets** [d6lts/drupal#51]
Problem with utf8 chars in quoting function in includes/common.inc in function "function drupal_to_js($var)"

Problem occurs in Views Admin in the "Filter"-Widget with a many-to-one relation:
project/admin/build/views/nojs/config-item/startseite_phase1/page/filter/field_from_ba_value_many_to_one

The function returns a json-string in 

`{
	"display": "\x3cform action=\"\"\x3e ... \x3c/form\x3e\n",
	"title": "Page: Filter \x3cem\x3eInhalt: Bezirksamtseingabe (field_from_ba) - Zulässige Werte\x3c/em\x3e konfigurieren",
	"url": "https://www.berlin.de/ba-spandau/buergerhaushalt/admin/build/views/ajax/config-item/startseite_phase1/page/filter/field_from_ba_value_many_to_one",
	"js": {
		"viewsAjax": {
			"formRelationships": {
				"edit-options-value": {
					"num": 1,
					"values": {
						"radio:options[operator]": ["or", "and", "not"]
					}
				}
			}
		}
	},
	"hilite": ".views-item-page-filter-field-from-ba-value-many-to-one"
}`

It should be
`"display": "\u003Cform action=\"\"\u003E ... \u003C/form\u003E\n",`

Fix found in Module jquery_update/patches/drupal_to_js_proper_json-D6.patch

**Comment by neffets** [comment]
[d6-issue-51.patch.txt](https://github.com/d6lts/drupal/files/4339092/d6-issue-51.patch.txt)

**Comment by dsnopek** [comment]
Fundamentally, this change makes sense to me! The code in the patch is actually from Drupal 7, in includes/json-encode.inc. I've made PR #56 which is working in my testing. Going to hold off for a bit to see if it can get a little more testing first.

**Comment by amorsent** [comment]
I'm trying to reconcile these changes with Pressflow's changes to drupal_to_js().
You will have to address this conflict if you try to pull these changes into D6LTS Pressflow (it's a bit behind BTW)


Pressflow dropped all this custom code and just uses json_encode() 
https://github.com/d6lts/pressflow/blob/master/includes/common.inc#L2563
```
function drupal_to_js($var) {
  // json_encode() does not escape <, > and &, so we do it with str_replace()
  return str_replace(array("<", ">", "&"), array('\u003c', '\u003e', '\u0026'), json_encode($var));
}
```

I've been using the Pressflow version for about a decade without issue.


The D7 code you refer to is actually a _fallback_ to support PHP < 5.3
For PHP >= 5.3.0 D7's [drupal_json_encode()](https://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_json_encode/7.x) actually just uses this:
```
// Encode <, >, ', &, and " using the json_encode() options parameter.
return json_encode($var, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT);
```

D8's version drop's the fallback logic and only uses the json_encode() logic.
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Serialization%21Json.php/function/Json%3A%3Aencode/8.2.x

**Differences**:
The D7/8 version encodes ' and " characters where the Pressflow version does not.
The D7 _fallback_ (and this current D6LTS version) **encodes** the following characters, where the D7/8 version leaves them un-encoded (but properly escaped):
"\\", "\b", "\t", "\n", "\f", "\r", "\/",


Is PHP < 5.3 support still a requirement for D6LTS?
If not, then it seems like we should probably just adopt the D7/8 json_encode() logic (which is similar, but an improvement to the version in Pressflow).

**Comment by dsnopek** [comment]
> Is PHP < 5.3 support still a requirement for D6LTS?

Unfortunately, yes, we officially support PHP 5.2 and even have a couple stubborn customers that are still using it.

I believe Pressflow is PHP 5.3+ anyway, so I think it'd be fine if Pressflow didn't merge these changes and stuck with what it already has.

Also, I could see an argument for having D6LTS also check for PHP >=5.3 and using `json_encode()` - if someone made a PR for that, there's a strong chance it'd go in.
