### ISSUE TITLE
One more theme.inc change

### ISSUE THREAD

**Issue by splash112** [d6lts/drupal#53]
Hi, 

One last theme.inc change that reduced errors on my site.
[theme_inc.zip](https://github.com/d6lts/drupal/files/4948198/theme_inc.zip)

**Comment by NiklasBr** [comment]
Can you do a pull request or just paste the diff here instead?

**Comment by splash112** [comment]
Sure, hope to learn how to do a pull request soon:

diff --git a/includes/theme.inc b/includes/theme.inc
index a47fa1e4aa..4683382d2a 100644
--- a/includes/theme.inc
+++ b/includes/theme.inc
@@ -1216,7 +1216,7 @@ function theme_links($links, $attributes = array('class' => 'links')) {
   global $language;
   $output = '';
 
-  if (count($links) > 0) {
+  if (!empty($links)) {
     $output = '<ul'. drupal_attributes($attributes) .'>';
 
     $num_links = count($links);

**Comment by splash112** [comment]
`diff --git a/includes/theme.inc b/includes/theme.inc
index a47fa1e4aa..4683382d2a 100644
--- a/includes/theme.inc
+++ b/includes/theme.inc
@@ -1216,7 +1216,7 @@ function theme_links($links, $attributes = array('class' => 'links')) {
   global $language;
   $output = '';
 
-  if (count($links) > 0) {
+  if (!empty($links)) {
     $output = '<ul'. drupal_attributes($attributes) .'>';
 
     $num_links = count($links);
`

**Comment by splash112** [comment]
Hi Niklas,

Maybe it works better in a mail.

diff --git a/includes/theme.inc b/includes/theme.inc
index a47fa1e4aa..4683382d2a 100644
--- a/includes/theme.inc
+++ b/includes/theme.inc
@@ -1216,7 +1216,7 @@ function theme_links($links, $attributes =
array('class' => 'links')) {
   global $language;
   $output = '';

-  if (count($links) > 0) {
+  if (!empty($links)) {
     $output = '<ul'. drupal_attributes($attributes) .'>';

     $num_links = count($links);

**Comment by NiklasBr** [comment]
@splash112 I created a PR for you, in the future you can do this yourself for simple changes right here on Github by editing the directly.

**Comment by dsnopek** [comment]
Thanks! I posted some review on the PR #54
