### ISSUE TITLE
I broke my d6 site

### ISSUE THREAD

**Issue by mikikuke** [d6lts/drupal#57]
I downloeaded files here on this git and uploaded it to my server.....
then I deleted my old setting file and used default.setting.php from this git and rename it to settings.php and updated my db info
in line  92

my site is broken now

**Comment by dsnopek** [comment]
Sorry your site got broken! Unfortunately, we're not able to provide support for a specific site here. Please contact one of the Drupal 6 LTS vendors listed on https://www.drupal.org/project/d6lts/
