### ISSUE TITLE
Why duplicate variable_get():s?

### ISSUE THREAD

**Issue by NiklasBr** [d6lts/drupal#6]
There are two calls to

```php
$log_sanitized_keys = variable_get('sanitize_input_logging', FALSE);
```

First on line [1679](https://github.com/d6lts/drupal/blob/941385030d49f34c87bebe961c9b1528b845e070/includes/bootstrap.inc#L1679) and then on line [1684](https://github.com/d6lts/drupal/blob/941385030d49f34c87bebe961c9b1528b845e070/includes/bootstrap.inc#L1684). I may be missing something, but to me it looks like only one is needed.

**Comment by dsnopek** [comment]
Thanks! This was just an oversight. Things like this can happen with private patches because the pool of people reviewing is much smaller than with public patches :-)
