### ISSUE TITLE
How do you build the release?

### ISSUE THREAD

**Issue by hanoii** [d6lts/drupal#7]
Just wondering if you have a special script or something? Can it be shared?

Thanks!

**Comment by dsnopek** [comment]
We have a script to add the packaging info to the .info files, but that's it. If that's what you're looking for, I could make a Gist? It's only like 30 lines of Python code.

**Comment by dsnopek** [comment]
Just in case, here's a gist with the script:

https://gist.github.com/dsnopek/43c54eef3b560df38cfcc388288b0833

**Comment by hanoii** [comment]
Thanks.. yeah.. I kind of maintain some D5 sites and was maybe planning on doing a similar in house releases like yours, that's why I asked for the script, thanks for sharing.
