### ISSUE TITLE
Regex in .htaccess to protect files and directories from prying eyes seems to have a typo

### ISSUE THREAD

**Issue by osopolar** [d6lts/drupal#72]
The last part of the regex `|\.bak|\.orig\.save)$">` does not look right, it seems that the `|` is missing before `\.save`, I think it should be `|\.bak|\.orig|\.save)$">`, at in least D9 looks like that. Imho it should match files php.orig and php.save … not php.orig.save

https://github.com/d6lts/drupal/commit/dd343835cf37c731c647a391d70e63d5e5c0b65c#r66853188

**Comment by dsnopek** [comment]
Good catch! I've committed a fix adding the `|` symbol
