### ISSUE TITLE
PHP 7 branch - Plan for release

### ISSUE THREAD

**Issue by emilymathew** [d6lts/drupal#8]
Hi @dsnopek,

Its great to know that there is a plan to support PHP 7 on Drupal 6 LTS. Shall I know when we can expect the release?

**Comment by dsnopek** [comment]
We don't have an exact timeline, but there's really only one small thing left that we're aware of to fix for Drupal 6 core.

**Comment by emilymathew** [comment]
Thank you @dsnopek . Shall I know what is left to fix. Is that the function sess_regenerate? 
What was the approach to identify the issues? I used php7cc.phar and php7mar to test the code. I am not sure whether I did it right, since it does not show any errors.

**Comment by dsnopek** [comment]
Yes, we need to fix `sess_regenerate()` to work in PHP 7 - currently it's just commented out. The issues were identified in testing. There aren't any easy PHP 7 syntax issues left in core (there's loads in contrib :-)).

**Comment by sblommers** [comment]
Maybe https://github.com/RCold/drupal6/ sheds some light on how sess_regenerate should apply to being compatible with php7? Just a guess, I jumped into this 5 minutes ago.

**Comment by hanoii** [comment]
@dsnopek I might need to jump into making a d6 site work on php7, can you provide some details on what's the issue with that particular function and what are the implications of having it commented out?

Thanks!

**Comment by dsnopek** [comment]
I believe the issue that led to it being commented out was that user login failed.

This function is meant to dispose of an old session and create a new one. Having it commented means that we aren't creating a new session, but continuing to use the old one (from when the user was anonymous), which I suspect has security implications.

**Comment by hanoii** [comment]
@dsnopek I see, are you running this branch on a production environment? And regardless.. is it up to date with the latest d6lts? I'll soon review myself, but if you can spare a sec to answer that's great! Appreciated!

**Comment by dsnopek** [comment]
We've been testing local clones of production sites, not live. The area we've been spending most time on lately is contrib - this lingering core issue seems like it won't be too hard to tackle. :-) We just haven't circled back here yet.

> And regardless.. is it up to date with the latest d6lts?

It is now! ;-)

**Comment by hanoii** [comment]
With #9 merged I wonder if we should just merge it into the main branch, at least there's gonna be more general feedback on it. Should be safe to be part of the d6lts releases.

**Comment by hanoii** [comment]
And out of curiosity just checked what https://github.com/RCold/drupal6/ did on this and it's exactly the same.

**Comment by dsnopek** [comment]
> With #9 merged I wonder if we should just merge it into the main branch, at least there's gonna be more general feedback on it. Should be safe to be part of the d6lts releases.

In general, I agree!

I don't think I actually want to say we support PHP 7 just yet, in case we missed something important, particularly with security. But so long as the changes don't break PHP 5.2 (the oldest version we have a stubborn client still on :-)) the changes should be fine in the main branch. I added a change that should allow `decode_entities()` to continue work with PHP 5.2, but I actually don't have a way to test that locally...

Relatedly, I updated the .htaccess file including the one generated for the files directory. It turns out that without that, on Apache, suddenly .php files in the user uploaded files directory were executable in my testing! I also tested the installer in PHP 7.2 - it was broken, so I added some small fixes for it too.

So, I guess the only remaining thing in order to merge into the main branch is to test that this doesn't break PHP 5.2

**Comment by dsnopek** [comment]
I created a PR (#10) to make the changes for this easier to see and review

**Comment by dsnopek** [comment]
I finally got a local dev env with PHP 5.2 working and, unfortunately, it gets this error:

```
PHP Parse error:  syntax error, unexpected T_FUNCTION in /app/includes/unicode.inc on line 354
```

The first thing that comes to mind is putting the code in another file, but seems messy...

**Comment by dsnopek** [comment]
Came up with an implementation that uses a class rather than a closure, which works in my testing on PHP 5.2, 5.6 and 7.2!

So, this is probably nearly ready to merge... If anyone can give any extra testing/review, that'd be awesome

**Comment by dsnopek** [comment]
I went ahead and merged it! I'd still appreciate testing and review, but we can do that on the main branch :-)

**Comment by dsnopek** [comment]
I made a release for this last week:

https://github.com/d6lts/drupal/releases/tag/6.45

So, closing :-)
